server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      info: master
      server:
        git:
          #uri: git@github.com:EiletXie/config-repo.git #Github上的git仓库名字
          uri: https://github.com/zhangyuangod/springcloud-config.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - springcloud-config
          #timeout: 15
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
